"""Add delivery fields

Revision ID: afbf13cd19ab
Revises: 86f1b6299984
Create Date: 2026-08-05 11:40:37.196466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbf13cd19ab'
down_revision = '86f1b6299984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_type')

    # ### end Alembic commands ###
